---
title: "Least-angle Regression (LARS)"
author: "OverFit Noise Group 5: Yahya Hussein, Andrew Farabow, Bryan Nguyen, Jack Jiang, Manning Luo, Shelby Neal"
date: "November 24, 2021"
output: 
  revealjs::revealjs_presentation:
    theme: beige
    highlight: zenburn
    widescreen: true
    mathjax: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```


## History of Lars

- LARS is an algorithm for fitting regressions to high-dimensional data
developed by Bradley Efron, Trevor Hastie, Iain Johnstone and Robert Tibshirani
- 

## Core Concepts 

```{r, echo = TRUE}
summary(cars)
```

## Why Use Lars

```{r}
plot(pressure)
```

## Mathematical / Statistical Walk Through 
$\hat{y}=\hat{B}_{0}+\hat{B}_{1}x$

----

part 2

----

## Baby Example 1
```{r}
plot(pressure)
```

## Baby Example 2
```{r}
plot(pressure)
```


## Lars using Crime
```{r}
plot(pressure)
```

## References
1. https://tibshirani.su.domains/ftp/lars.pdf
2. https://ir.library.louisville.edu/cgi/viewcontent.cgi?article=3487&context=etd

## Wrap Up 

